version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - cache-{{ checksum "Pipfile.lock" }}
          - cache-

      - run:
          name: install dependencies
          command: pipenv sync --dev

      - save_cache:
          paths:
            - ~/.local
            - ~/.cache
          key: cache-{{ checksum "Pipfile.lock" }}
        
      - run:
          name: run tests
          command: pipenv run pytest --flake8

      - store_artifacts:
          path: test-reports
          destination: test-reports
